### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by pocketssss** [wyozi-gmod/imgui#10]
[https://youtu.be/Yg83ksJCOfo](url)

lul 

`function ENT:DrawTranslucent()
        self:DrawModel()
        if LocalPlayer():GetPos():Distance(self:GetPos())>500 then return end

    
        local w = 1000
        local h = 376
    

        if imgui.Entity3D2D(self,Vector(22, -20, 30), Angle(0, 90, 90), 0.1, 200, 150) then

    
            draw.RoundedBox(0,0,0,350,500,Color(130,70,30,200))
            if imgui.xTextButton("Soda", "!Roboto@24", 30, 30, 100, 100) then
                -- the xTextButton function returns true, if user clicked on this area during this frame
                print("yay, we were clicked :D")
              end
            
            imgui.End3D2D()
          end
    end`

**Comment by wyozi** [comment]
Strange. What does it say if you enable `developer` cvar?
