### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Sticks6110** [wyozi-gmod/imgui#12]
Ever since ive got imgui my game crashes heres the script

''include("shared.lua")
local imgui = include("imgui.lua")

surface.CreateFont( "Font", {
	font = "Arial", -- Use the font-name which is shown to you by your operating system Font Viewer, not the file name
	extended = false,
	size = 100,
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "Font2", {
	font = "Arial", -- Use the font-name which is shown to you by your operating system Font Viewer, not the file name
	extended = false,
	size = 30,
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

function ENT:Draw()

	self:DrawModel()

	local Pos = self:GetPos()
	local Ang = self:GetAngles()
	local temp = LocalPlayer():GetNetworkedInt( "temp", 0)

	Ang:RotateAroundAxis(Ang:Up(), 90)

	cam.Start3D2D(Pos + Ang:Up() * 10.6, Ang, 0.11 )
	imgui.Start3D2D(Pos + Ang:Up() * 10.6, Ang, 0.11 )

	draw.WordBox(8, -80, -150, "", "Font", Color(120, 120, 255, 0), Color(255, 255, 255, 0))
	draw.RoundedBox(0, -135, -145, 275, 290, Color(120,120,120,255))
	draw.SimpleText("$"..self.Entity:GetMoneyAmount(), "Font", 0, -100, Color(255, 255, 255, 255),1 ,1)
	draw.RoundedBox(0, -102, -32, 204, 30, Color(75,75,75,255))
	draw.RoundedBox(0, -102, 28, 204, 30, Color(75,75,75,255))

	draw.RoundedBox(0, -100, -30,  self.Entity:GetTemp() * 2, 25, Color(100,100,100,255))
	draw.RoundedBox(0, -100, 30,  self.Entity:GetPower() * 2, 25, Color(100,100,100,255))

	draw.SimpleText("Temperature: "..self.Entity:GetTemp(), "Font2", 0, -18, Color(255, 255, 255, 255),1 ,1)
	draw.SimpleText("Power: "..self.Entity:GetPower(), "Font2", 0, 43, Color(255, 255, 255, 255),1 ,1)

	if imgui.xTextButton("Foo bar", "!Roboto@24", -100, 100, 200, 25) then
      -- the xTextButton function returns true, if user clicked on this area during this frame
      print("yay, we were clicked :D")
    end

	cam.End3D2D()
	imgui.End3D2D()

end''

**Comment by wyozi** [comment]
Remove `cam.Start3D2D(Pos + Ang:Up() * 10.6, Ang, 0.11 )` and `cam.End3D2D()`. IMGUI handles those for you

**Comment by Sticks6110** [comment]
Still crashes ive done some testing and when ever i launch the printer that has this script 
the game crashes, do i have to change the draw to imgui befor the 2d3d stuff

**Comment by Sticks6110** [comment]
nvm i put imgui instead of draw it didnt draw anything but it didnt crash when i threw it???

**Comment by Sticks6110** [comment]
When it crashes it dosent lag it just crashes

**Comment by wyozi** [comment]
Can you post the new code in whole?

**Comment by Sticks6110** [comment]
yup

''include("shared.lua")
local imgui = include("imgui.lua")

surface.CreateFont( "Font", {
	font = "Arial", -- Use the font-name which is shown to you by your operating system Font Viewer, not the file name
	extended = false,
	size = 100,
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "Font2", {
	font = "Arial", -- Use the font-name which is shown to you by your operating system Font Viewer, not the file name
	extended = false,
	size = 30,
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

ENT.RenderGroup = RENDERGROUP_TRANSLUCENT

function ENT:DrawTranslucent()

	self:DrawModel()

	local Pos = self:GetPos()
	local Ang = self:GetAngles()
	local temp = LocalPlayer():GetNetworkedInt( "temp", 0)

	Ang:RotateAroundAxis(Ang:Up(), 90)

	imgui.Start3D2D(Pos + Ang:Up() * 10.7, Ang, 0.11 )

	draw.WordBox(8, -80, -150, "", "Font", Color(120, 120, 255, 0), Color(255, 255, 255, 0))
	draw.RoundedBox(0, -135, -145, 275, 290, Color(120,120,120,255))
	draw.SimpleText("$"..self.Entity:GetMoneyAmount(), "Font", 0, -100, Color(255, 255, 255, 255),1 ,1)
	draw.RoundedBox(0, -102, -32, 204, 30, Color(75,75,75,255))
	draw.RoundedBox(0, -102, 28, 204, 30, Color(75,75,75,255))

	draw.RoundedBox(0, -100, -30,  self.Entity:GetTemp() * 2, 25, Color(100,100,100,255))
	draw.RoundedBox(0, -100, 30,  self.Entity:GetPower() * 2, 25, Color(100,100,100,255))

	draw.SimpleText("Temperature: "..self.Entity:GetTemp(), "Font2", 0, -18, Color(255, 255, 255, 255),1 ,1)
	draw.SimpleText("Power: "..self.Entity:GetPower(), "Font2", 0, 43, Color(255, 255, 255, 255),1 ,1)

	if imgui.xTextButton("Foo bar", "!Roboto@24", -100, 100, 200, 25) then
      print("clicked")
    end

	imgui.End3D2D()

end''

**Comment by BeastBomber23** [comment]
that is all client side

**Comment by Sticks6110** [comment]
Ive done some more revisions to the script its not imgui thankfuly ssomething else is crashing my game in this

**Comment by wyozi** [comment]
Well, the code looks ok to me. Feel free to reopen if you figure out it is somehow related to imgui

**Comment by Sticks6110** [comment]
k thanks :)

**Comment by Sticks6110** [comment]
what is AddCsLuaFile'D could that be my problem??

**Comment by Sticks6110** [comment]
oml i just asked that question nvm

**Comment by wyozi** [comment]
That would not be the problem
