### ISSUE TITLE
Game still crashing

### ISSUE THREAD

**Issue by Sticks6110** [wyozi-gmod/imgui#13]
I know ive made a issue about this befor but it was closed and im still geting crashes i think it might have something to do with imgui ive made a download link to my addon im making http://www.mediafire.com/file/xn4c2twkilbhfxg/BeastPrinters.zip/file ive trimemd the code a bit and crashes are not as often but i still dont know how to fix them

**Comment by wyozi** [comment]
Can you create a github repo or something? Reading through zip is hard

**Comment by Sticks6110** [comment]
sure https://github.com/BeastBomber23/PrintTemp :)

**Comment by wyozi** [comment]
One thing I noticed is you have `ENT.RenderGroup = RENDERGROUP_TRANSLUCENT` while still doing the drawing inside `ENT:Draw` instead of `ENT:DrawTranslucent`. I doubt that would crash the game though

**Comment by Sticks6110** [comment]
i tried that it still crashes???

**Comment by Sticks6110** [comment]
K so ive found some information im going over ive found, i found the informatiopn here https://steamcommunity.com/app/65930/discussions/0/34095131778460642/

**Comment by Sticks6110** [comment]
when i had steam test my files the validation of 158 files were missing

**Comment by Sticks6110** [comment]
nothings working ive looked up solutions to that error code but nothing works

**Comment by Sticks6110** [comment]
i think its a client side problem... get it because the problem is most likely my pc

**Comment by wyozi** [comment]
Yeah, the error looks like something not caused by the rendering engine

**Comment by BeastBomber23** [comment]
ive got another error but this time from console

[DarkRP] addons/beastprinters/lua/entities/printer/imgui.lua:294: tried to end invalid render instance
  1. error - [C]:-1
   2. End3D2D - gamemodes/darkrp/gamemode/modules/workarounds/sh_workarounds.lua:164
    3. End3D2D - addons/beastprinters/lua/entities/printer/imgui.lua:294
     4. unknown - addons/beastprinters/lua/entities/printer/cl_init.lua:89

**Comment by Sticks6110** [comment]
looks like i have fixed the problem spent a few hours updating and checking all my drivers
