### ISSUE TITLE
Buttons wont work

### ISSUE THREAD

**Issue by Gmod18** [wyozi-gmod/imgui#17]
The button wont work for some reason i dont have anymore to say cause idk whats making it not get hightlighted

![Garry's Mod Screenshot 2020 04 18 - 16 43 27 91](https://user-images.githubusercontent.com/63930358/79670837-cc8a1b00-8193-11ea-88c9-85e6ea23403a.png)

**Comment by Gmod18** [comment]
i forgot to add that the buttons in this image are floating because i thought it might be the collison box of the prop

**Comment by Gmod18** [comment]
i raised the buttons higher and they work but they are like 3 feet above the table so is there a way to make them work on the normal level

**Comment by wyozi** [comment]
The problem here is the table's collision model. The library could use a feature to ignore certain entities in input collisions

**Comment by wyozi** [comment]
I made an experimental branch: https://github.com/wyozi-gmod/imgui/pull/18

Can you test it out to see if it works? You can just provide the table entity as the last parameter to `Start3D2D`

**Comment by Gmod18** [comment]
imgui.Start3D2D(Pos + Ang:Up() * 37.6, Ang, 0.11, 10, 10, self) wont work i get errors but the normal code looks like this imgui.Start3D2D(Pos + Ang:Up() * 37.6, Ang, 0.11)

**Comment by Gmod18** [comment]
also this is completly different but i keep getting this error 


''[DarkRP] addons/fallout_chems/lua/entities/chem_workbench/imgui.lua:295: tried to end invalid render instance
  1. error - [C]:-1
   2. End3D2D - gamemodes/darkrp/gamemode/modules/workarounds/sh_workarounds.lua:164
    3. End3D2D - addons/fallout_chems/lua/entities/chem_workbench/imgui.lua:295
     4. unknown - addons/fallout_chems/lua/entities/chem_workbench/cl_init.lua:263
''

**Comment by Gmod18** [comment]
nvm IT WORKS :) THANK YOU SO MUCH i can fix so many of my addons that look weird now

**Comment by Gmod18** [comment]
this has helped me so much

**Comment by Gmod18** [comment]
my only problem now is 

[DarkRP] addons/fallout_chems/lua/entities/chem_workbench/imgui.lua:294: tried to end invalid render instance
  1. error - [C]:-1
   2. End3D2D - gamemodes/darkrp/gamemode/modules/workarounds/sh_workarounds.lua:164
    3. End3D2D - addons/fallout_chems/lua/entities/chem_workbench/imgui.lua:294
     4. unknown - addons/fallout_chems/lua/entities/chem_workbench/cl_init.lua:274

**Comment by wyozi** [comment]
Are you using `imgui.End3D2D` correctly? It needs to be *inside* the `if imgui.Start3D2D` block

**Comment by Gmod18** [comment]
it all works now thanks
