### ISSUE TITLE
Network Send

### ISSUE THREAD

**Issue by Gmod18** [wyozi-gmod/imgui#19]
Im trying to make a purchasing system but net.Send keeps breaking imgui.

          net.Start("PurchaseItem")
          net.Send( LocalPlayer() )

**Comment by Gmod18** [comment]
i have gone through a bunch of different forums set everything up server side correctly idk about client side thoe thats the only code i have for networking in client

**Comment by wyozi** [comment]
`net.Send` is serverside. Try `net.SendToServer()`

**Comment by Gmod18** [comment]
that works sorry for the small error on my behalf but also thank you for the solution :)
