### ISSUE TITLE
Ran into a Problem

### ISSUE THREAD

**Issue by KCiMbo** [wyozi-gmod/imgui#20]
I believe that the problem is just with me but I honestly can't get it to work. Iam getting this error when spawning in my entity. If anyone would be able to help me that would be amazing I just started gmod lua and have no idea what Iam doing wrong.

![image](https://user-images.githubusercontent.com/47118246/83809948-9d822700-a6b7-11ea-9235-b987197815b1.png)

shared.lua
![image](https://user-images.githubusercontent.com/47118246/83810147-efc34800-a6b7-11ea-8b5c-71cc3426a00c.png)

init.lua
![image](https://user-images.githubusercontent.com/47118246/83810178-fea9fa80-a6b7-11ea-8e42-786322fa8b30.png)

cl_init.lua
![image](https://user-images.githubusercontent.com/47118246/83810324-3d3fb500-a6b8-11ea-9599-1f558e571d45.png)

**Comment by wyozi** [comment]
`Start3d2d` takes vectors but youre passing in just numbers. See the example in readme
