### ISSUE TITLE
Many scenes | I need help

### ISSUE THREAD

**Issue by soberaja** [wyozi-gmod/imgui#21]
Hello 
I writing because I have a problem. I want to make 3d2d menu with multi scenes, I mean you have a main scene and there you have a button for example "test1" when you click "test1" then will open a new scene. I don't know how can I make something like that or is it possible.
Have a nice day 
Soberaja

**Comment by wyozi** [comment]
You can make that by storing the active scene in a variable.

Something like this
```lua
local scene = nil
hook.Add("PostDrawTranslucentRenderables", "MultiSceneIMGUI", function()

  if imgui.Start3D2D(Vector(980, -83, -79), Angle(0, 270, 90), 0.1, 200, 150) then
    if scene == "second" then
       -- draw second scene
    else
       if imgui.xTextButton("Enter next scene", "!Roboto@24", 0, 30, 100, 25, 1, Color(255,255,255), Color(0,0,255), Color(255,0,0)) then
          scene = "second"
       end
    end
    imgui.End3D2D()
end)
```

If your IMGUI is in an entity, store the variable inside the entity instead of a local variable.

**Comment by soberaja** [comment]
Thanks :D
