### ISSUE TITLE
Imgui End Problems

### ISSUE THREAD

**Issue by Sticks6110** [wyozi-gmod/imgui#24]
When ever i walk away from my imgui creation i get this error

[DarkRP] addons/fallout_chems/lua/entities/chem_workbench/imgui.lua:294: tried to end invalid render instance
  1. error - [C]:-1
   2. End3D2D - gamemodes/darkrp/gamemode/modules/workarounds/sh_workarounds.lua:164
    3. End3D2D - addons/fallout_chems/lua/entities/chem_workbench/imgui.lua:294
     4. unknown - addons/fallout_chems/lua/entities/chem_workbench/cl_init.lua:436

The line of code on cl_init is 

  imgui.End3D2D()

and the line of code in imgui is

  cam.End3D2D()

**Comment by TomDotBat** [comment]
Check you're not ending the instance twice or something along those lines. Usually it would crash your game if it wasn't for the DarkRP workaround. If you can't seem to find the problem drop your code in here, I'll take a look :)

**Comment by wyozi** [comment]
Also make sure `imgui.End3D2D` is inside the `if imgui.Start3D2D then ... end`

**Comment by Sticks6110** [comment]
Do you mean something like this wyozi

    imgui.End3D2D()
    
  end

**Comment by TomDotBat** [comment]
It should look a somewhat like this:
```lua
if imgui.Start3D2D(pos, ang, scale) then
  --Draw your UI here...
  imgui.End3D2D()
end
```

Notice that `imgui.End3D2D()` is put right at the end of the if statement, you should put it there, not outside of it. :)

**Comment by Sticks6110** [comment]
Is the problem i have 2 of them it kinda looks like

if imgui.Start3D2D(pos, ang, scale) then
  --Draw your UI here...
  imgui.End3D2D()
end

if imgui.Start3D2D(pos, ang, scale) then
  --Draw your UI here...
  imgui.End3D2D()
end

but lots more code

**Comment by wyozi** [comment]
That looks good to me. Make sure those are the only ones starting and ending imgui in the file.

Also try scroll up before the "tried to end invalid render instance" error. Maybe there is another error up there causing this error.

**Comment by Sticks6110** [comment]
Ive done that befor theres nothing its the same for the first error

**Comment by wyozi** [comment]
Would need to see the code to be able to say better
