### ISSUE TITLE
Error when fade out

### ISSUE THREAD

**Issue by Sticks6110** [wyozi-gmod/imgui#26]
I get a error when it fades out and the error is at line 428 which is imgui.End3D2D(). Ive been having this problem for a while but waited to fix it because it wasnt a game breaking bug so it was at the bottom of my list to fix. Can you please help me.

**Comment by wyozi** [comment]
What's the error?

**Comment by Sticks6110** [comment]
[fallout_chems] addons/fallout_chems/lua/entities/chem_workbench/imgui.lua:294: tried to end invalid render instance
  1. error - [C]:-1
   2. End3D2D - gamemodes/darkrp/gamemode/modules/workarounds/sh_workarounds.lua:164
    3. End3D2D - addons/fallout_chems/lua/entities/chem_workbench/imgui.lua:294
     4. unknown - addons/fallout_chems/lua/entities/chem_workbench/cl_init.lua:429 (x194)

Hmm looks like my error changed after messing with it for a bit the error is now at 429 and that line is " end" and its below imgui.End3D2D()

**Comment by wyozi** [comment]
Looks like an error with how imgui is being used. The `imgui.End3D2D` call is probably outside the if. If you post the full imgui code in cl_init.lua I would be able to tell better

**Comment by Sticks6110** [comment]
Thanks that worked it was outside the if i accidently somehow put a end befor the imgui instead of outside.
