### ISSUE TITLE
Why is imgui bugging if another condition is in the     if (imgui.Entity3D2D(self, Vector(-71, -95, 2), Angle(0, 90, 0), 0.1)) then

### ISSUE THREAD

**Issue by Pdzly** [wyozi-gmod/imgui#32]
If i make it to for example:

    if (imgui.Entity3D2D(self, Vector(-71, -95, 2), Angle(0, 90, 0), 0.1), LocalPlayer():IsAdmin()) then
it function if the user started with the permission but if he is for example not anymore admin and become admin again it wont work anymore

Is this a thing from gmod or its a glitch?

**Comment by wyozi** [comment]
I don't know how that code even works. Anyway, IsAdmin check should be before Entity3D2D call

**Comment by Pdzly** [comment]
ok i tested it both ways
but still nope

**Comment by wyozi** [comment]
Not sure then. Would have to see more code to say for sure

**Comment by Pdzly** [comment]
yeah of course i will make you an example
