### ISSUE TITLE
Errorless CTD on physgun interactions and re-entering render range

### ISSUE THREAD

**Issue by Pilotfish62873** [wyozi-gmod/imgui#33]
I've been getting routine CTDs when I pull out my physgun near a panel, move an entity the panel is tied to, or when I leave the rendering distance specified in imgui.Start3D2D and then return again.

This happens even when the code is just an empty context:

imgui.Start3D2D(self:GetPos() + self:GetForward () * 42.5 + self:GetUp() * 48.75, ang, 0.01)
imgui.End3D2D()

Could be an error on my part but the lack of error messages has me stumped. This doesn't happen with regular cam.Start3D2D.

(Fantastic work by the way - this is really cool stuff)

**Comment by wyozi** [comment]
Interesting. Did you try wrapping the End3D2D in an if (so it only gets called when Start3D2D returns true)? Definitely sounds like something breaking with the camera context stacks

**Comment by Pilotfish62873** [comment]
I think that did it - thanks! I was also not using Entity3D2D (thanks for making that - really useful!)

I'll let you know if any more issues crop up, but once again thanks for making this. I'll throw up some WIP images on your "in the wild" page.
