### ISSUE TITLE
How to migrate from tdui?

### ISSUE THREAD

**Issue by Gravy59** [wyozi-gmod/imgui#38]
I used [TDUI](https://github.com/wyozi/3d2d-imgui) in my addon before finding this, is it similar or will I have to do a big change in the codebase?

**Comment by wyozi** [comment]
It's quite different! imgui tries to rely on native gmod draw functions to draw the UI as much as possible whereas TDUI provided custom functions for everything.

I'd say it's worth sticking with TDUI, if you're not planning any big changes to the UI and everything seems to work fine. Definitely recommend imgui for all the new development though

**Comment by Gravy59** [comment]
Thanks! I will keep that in mind.
