### ISSUE TITLE
Render different stuff

### ISSUE THREAD

**Issue by sentinel-commit** [wyozi-gmod/imgui#39]
It's maybe my bad but how to create different render for different player?
For example, I want to create a bank system where player could log into their account and show their money. But what happens to me is that when you press button on 1. entity, it's pressed on 2. entity that is elsewhere, so when player pressed login, it displayed his money on every single entity on the map.

**Comment by wyozi** [comment]
IMGUI is a completely clientside library and you are in full control of when and what you render. So if you follow the entity method of rendering IMGUIs (see e.g. https://github.com/wyozi-gmod/imgui#networking-data), it should be visible for each entity individually.

Networking and state is a bit of a wide topic, so hard to give more specific advice 🤷

**Comment by sentinel-commit** [comment]
Alright thank you, I'll take a look into it
