### ISSUE TITLE
How to rotate TextButton and text ?

### ISSUE THREAD

**Issue by IbrahimIsazade** [wyozi-gmod/imgui#43]
Hi guys. I wanted to make a custom printer for classic DarkRP and I stuck in rotating procces. As far as I know imgui doesn't support rotating directly. I've tried to ask Copilot and Chat-GPT 3.5 but both of them didn't satisfy me. Here's the pic:
![Screenshot 2024-03-28 203813](https://github.com/wyozi-gmod/imgui/assets/150580444/d0ef9295-b64e-4819-b132-d9625d57a117)
 With red pen I marked where I'd love to see the button.
 
 Part of my code (cl_init.lua):
```lua
 function ENT:Draw()
	self:DrawModel()
	if imgui.Entity3D2D(self, Vector(-12, 12, 7.9), Angle(0, 0, 0), 0.1) then
		self:SetColor(Color(70, 70, 70))
    	surface.SetDrawColor(70, 70, 70)
    	surface.DrawRect(10, 10, 210, 220)
    	draw.SimpleTextOutlined(self:GetMoneyAmount(), "MoneyFont", 0, 0, Color( 255, 255, 255), TEXT_ALIGN_LEFT, TEXT_ALIGN_TOP, 1, Color( 255, 255, 255 ))

    	if imgui.xTextButton("Take", "!Roboto@24", 0, 30, 100, 25, 1, Color(255,255,255), Color(180,180,180), Color(120,120,120)) then
	      net.Start("TakeMoney")
	      net.WriteEntity(self)
	      net.SendToServer()
	    end

    	imgui.End3D2D()
  	end
end
```

**Comment by wyozi** [comment]
You can rotate it by changing the values to `Angle(x, y, z)`

**Comment by IbrahimIsazade** [comment]
> You can rotate it by changing the values to `Angle(x, y, z)`
thank u.
