### ISSUE TITLE
DrawTexturedRect with "color" material

### ISSUE THREAD

**Issue by xaviergmail** [wyozi-gmod/imgui#6]
https://github.com/wyozi-gmod/imgui/blob/35473f1458c7f6faabe41341734738b805c72263/imgui.lua#L363-L369

Is there a reason for using DrawTexturedRect opposed to DrawRect, seeing as colorMat can't be changed?

**Comment by wyozi** [comment]
This is probably legacy code ported directly from TDUI, so I'm not sure. I can very vaguely remember `surface.DrawRect` not working perfectly in the 3D2D context, but I wouldn't bet on that.
