### ISSUE TITLE
Consider switching to MIT license or other

### ISSUE THREAD

**Issue by xaviergmail** [wyozi-gmod/imgui#7]
I would like to use this library without the GPL having a leash on me, more specifically needing to publish source code along with installation instructions to the public.

This is unfortunately a blocking issue for my commissioned work as well as other personal projects.

**Comment by wyozi** [comment]
Changed. It was initially GPL due to some previous incidents, but it's not like a license is a major blocker for most of gmod community anyway.

Hopefully this way at least a few more people find some use in the library.
