### ISSUE TITLE
imgui, FOV inconsistent on swep.

### ISSUE THREAD

**Issue by EvieMae** [wyozi-gmod/imgui#9]
I'm trying to make a swep that works similarly to the pipboy, however the viewmodel of the swep's fov and the players fov seems to make the buttons not work correctly.

**Comment by wyozi** [comment]
Hmm, you've placed the IMGUI on top of viewmodel? How do you do the clicking?

**Comment by EvieMae** [comment]
I haven't got that far yet but It would be checking the input.

But yeah the 3d2d is on the viewmodel

**Comment by EvieMae** [comment]
I have no problem checking the input, its just the mouse doesn't correctly work.

**Comment by wyozi** [comment]
Do you mean hovering works (and changes the button look) but clicking won't?

**Comment by EvieMae** [comment]
Hovering doesn't work correctly on anything but 90fov.

**Comment by wyozi** [comment]
Can you share a minimum viable code to reproduce the error? It'd be easier for me to say what's wrong

**Comment by EvieMae** [comment]
Of course, I look into sending it later today.

**Comment by EvieMae** [comment]
This was solved by making an internal cursor within the 3D2D interface and using PlayerMovement hook to disable turning and turning that into adjustments to the internal crosshair.
